modLoader = "javafml"
loaderVersion = "${forge_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/cScotPlay/BasicNetherOres/issues" #optional


[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    credits = "${mod_credits}" #optional
    authors = "${mod_author}"
    description = '''${mod_description}'''
    logoFile = "bno-logo.png"
    displayURL="https://minecraft.curseforge.com/projects/basic-nether-ores" #optional (displayed in the mod UI)

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"
